package sbnz.visitserbia.model;

public enum AttractionType {

    NATURE, HISTORICAL, VIEWPOINT, CAVE,
    LAKE, RIVER, SPA_RESORT, PARK,
    MUSEUM, ART_GALLERY,
    MONASTERY, CHURCH, MOSQUE,
    MOUNTAIN, VILLAGE,
    FAST_FOOD, RESTAURANT, TRADITIONAL_KITCHEN_RESTAURANT,
    NIGHT_CLUB, CAFFE,
    CINEMA, THEATRE,
    SHOPPING_MALL, ZOO,
    ACTIVITY
}
