package sbnz.visitserbia.model;

public enum PreferenceEnum {
    CITY, NATURE,
    FAST_FOOD, TRADITIONAL_KITCHEN, RESTAURANTS,
    INTERESTED_IN_CULTURE, NOT_INTERESTED_IN_CULTURE,
    SHOPPING_YES, SHOPPING_NO,
    CINEMA_AND_THEATRE_YES, CINEMA_AND_THEATRE_NO,
    ANIMALS_YES, ANIMALS_NO,
    WATER_YES, WATER_NO,
    MONASTERIES_YES, MONASTERIES_NO,
    ART_YES, ART_NO,
    REST_YES, REST_NO,
    ANYTHING, ANYWHERE, DOES_NOT_MATTER
}
