package rules;
import java.util.ArrayList;
import sbnz.visitserbia.model.RegisteredUser
import sbnz.visitserbia.DTOs.AttractionPopularityReportDTO
import sbnz.visitserbia.model.Result
import sbnz.visitserbia.model.Attraction

global ArrayList<Result> allResults;
global ArrayList<Attraction> allAttractions;

query "Least popular attractions"
    $mean: Number() from accumulate(
        Attraction($timesRecommended: timesRecommended)
        from allAttractions,
        average($timesRecommended))

    $leastPopular: ArrayList() from collect (
        Attraction(timesRecommended < $mean) from allAttractions)
end

query "Medium popular attractions"
    $mean: Number() from accumulate(
        Attraction($timesRecommended: timesRecommended)
        from allAttractions,
        average($timesRecommended))

    $mediumPopular: ArrayList() from collect (
        Attraction(timesRecommended >= $mean, timesRecommended < 2*$mean) from allAttractions)
end

query "Most popular attractions"
    $mean: Number() from accumulate( Attraction($timesRecommended: timesRecommended)
        from allAttractions,
        average($timesRecommended))

    $mostPopular: ArrayList() from collect (
        Attraction(timesRecommended >= 2*$mean) from allAttractions)
end
