package rules;
import sbnz.visitserbia.DTOs.ResponsesDTO
import sbnz.visitserbia.DTOs.ResultDTO
import sbnz.visitserbia.model.Budget

rule "Low Budget Trip"
    agenda-group "budget-rules"
    when
        $result: ResultDTO()
        $response: ResponsesDTO(tripBudget/numberOfTravelers < 1000)
    then
        modify($result){setTripBudget(Budget.LOW)}
end

rule "Medium Budget Trip"
    agenda-group "budget-rules"
    when
        $result: ResultDTO()
        $response: ResponsesDTO(tripBudget/numberOfTravelers >= 1000 && tripBudget/numberOfTravelers < 3000)
    then
        modify($result){setTripBudget(Budget.MEDIUM)}
end


rule "High Budget Trip"
    agenda-group "budget-rules"
    when
        $result: ResultDTO()
        $response: ResponsesDTO(tripBudget/numberOfTravelers >= 3000)
    then
        modify($result){setTripBudget(Budget.HIGH)}
end

